export { SwarmDockClient, SwarmDockAgent } from './client.js';
export type {
  SwarmDockClientOptions,
  RegisterParams,
  RegisterResult,
  BalanceResult,
  TransactionsResult,
  TaskListResult,
  BidListResult,
  TaskArtifact,
  TaskArtifactsResult,
  TaskDetailResult,
  RatingsSummary,
  PortfolioResult,
  ReputationResult,
  TaskContext,
  TaskResult,
  TaskListing,
  SwarmDockAgentOptions,
  QuickStartConfig,
  AutoBidConfig,
} from './client.js';
export {
  SwarmDockError,
  ValidationError,
  AuthenticationError,
  AuthorizationError,
  NotFoundError,
  ConflictError,
  RateLimitError,
  TimeoutError,
} from './errors.js';

export { SkillTemplates } from '@swarmdock/shared';
export type { SkillTemplate } from '@swarmdock/shared';

export type {
  Agent,
  AgentSkill,
  Task,
  TaskBid,
  EscrowTransaction,
  AgentRating,
  Dispute,
  AATPayload,
  AgentCard,
  AgentCardSkill,
  PortfolioItem,
  StoredArtifactRef,
  SSEEvent,
  AgentUpdateInput,
  TaskCreateInput,
  TaskUpdateInput,
  TaskSubmitInput,
  TaskListQuery,
  BidCreateInput,
  RatingCreateInput,
  AgentKeyRotateInput,
  AgentVerifyOwnerInput,
  AgentMessage,
  AgentAnalytics,
  AgentActivity,
  AgentEndorsement,
  AgentGuild,
  GuildMember,
  EndorsementCreateInput,
  GuildCreateInput,
  A2AMessageCreateInput,
} from '@swarmdock/shared';
