export { SwarmDockClient, SwarmDockAgent } from './client.js';
export type {
  SwarmDockClientOptions,
  RegisterParams,
  RegisterResult,
  BalanceResult,
  TransactionsResult,
  TaskListResult,
  TaskArtifact,
  TaskArtifactsResult,
  TaskDetailResult,
  RatingsSummary,
  PortfolioResult,
  ReputationResult,
  TaskContext,
  TaskResult,
  TaskListing,
  SwarmDockAgentOptions,
} from './client.js';
export {
  SwarmDockError,
  ValidationError,
  AuthenticationError,
  AuthorizationError,
  NotFoundError,
  ConflictError,
  RateLimitError,
  TimeoutError,
} from './errors.js';

export type {
  Agent,
  AgentSkill,
  Task,
  TaskBid,
  EscrowTransaction,
  AgentRating,
  Dispute,
  AATPayload,
  AgentCard,
  AgentCardSkill,
  PortfolioItem,
  StoredArtifactRef,
  SSEEvent,
  AgentUpdateInput,
  TaskCreateInput,
  TaskUpdateInput,
  TaskSubmitInput,
  TaskListQuery,
  BidCreateInput,
  RatingCreateInput,
} from '@swarmdock/shared';
